[package]
name = "dirtyqueue-derive"
version = "0.1.1"
edition = "2024"
description = "dirtyqueue is a thread and async safe, durable filesystem based queue (derive macros)"
authors = ["Erik Hollensbe <git@hollensbe.org>"]
license = "MIT"
homepage = "https://github.com/erikh/dirtyqueue"
repository = "https://github.com/erikh/dirtyqueue"
keywords = ["queue", "filesystem", "durable", "threadsafe", "serde"]

[dependencies]
quote = "^1"
syn = "^2"

[lib]
proc-macro = true
